2022-04-11 10:39:40,955 - pyswarms.single.global_best - INFO - Optimize for 1000 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-04-11 10:39:41,463 - pyswarms.single.global_best - INFO - Optimization finished | best cost: 2.0282442667053933, best pos: [1.01288672 1.00115171]
2022-04-11 11:00:27,529 - pyswarms.single.global_best - INFO - Optimize for 1000 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-04-11 11:00:27,818 - pyswarms.single.global_best - INFO - Optimization finished | best cost: 2.0059052386539644, best pos: [1.00289925 1.00004917]
2022-04-11 11:01:02,796 - pyswarms.single.global_best - INFO - Optimize for 1000 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-04-11 11:01:03,087 - pyswarms.single.global_best - INFO - Optimization finished | best cost: 2.0232935030148966, best pos: [1.0106523  1.00093727]
2022-04-11 11:01:51,905 - pyswarms.single.global_best - INFO - Optimize for 1000 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-04-11 11:01:52,189 - pyswarms.single.global_best - INFO - Optimization finished | best cost: 2.055524194028904, best pos: [1.02555641 1.00187736]
2022-04-11 11:12:34,017 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (2,)
Traceback (most recent call last):
  File "C:\Users\igorp\OneDrive\Pulpit\Studia\Inteligencja Obliczeniowa\venv\lib\site-packages\pyswarms\backend\generators.py", line 81, in generate_swarm
    pos = center * np.random.uniform(
  File "mtrand.pyx", line 1134, in numpy.random.mtrand.RandomState.uniform
  File "_common.pyx", line 579, in numpy.random._common.cont
  File "_common.pyx", line 496, in numpy.random._common.cont_broadcast_2
  File "__init__.pxd", line 742, in numpy.PyArray_MultiIterNew3
ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (10, 2) and arg 1 with shape (10, 6).
2022-04-11 11:12:48,922 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (2,)
Traceback (most recent call last):
  File "C:\Users\igorp\OneDrive\Pulpit\Studia\Inteligencja Obliczeniowa\venv\lib\site-packages\pyswarms\backend\generators.py", line 81, in generate_swarm
    pos = center * np.random.uniform(
  File "mtrand.pyx", line 1134, in numpy.random.mtrand.RandomState.uniform
  File "_common.pyx", line 579, in numpy.random._common.cont
  File "_common.pyx", line 496, in numpy.random._common.cont_broadcast_2
  File "__init__.pxd", line 742, in numpy.PyArray_MultiIterNew3
ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (10, 2) and arg 1 with shape (10, 6).
2022-04-11 11:13:01,645 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (2,)
Traceback (most recent call last):
  File "C:\Users\igorp\OneDrive\Pulpit\Studia\Inteligencja Obliczeniowa\venv\lib\site-packages\pyswarms\backend\generators.py", line 81, in generate_swarm
    pos = center * np.random.uniform(
  File "mtrand.pyx", line 1134, in numpy.random.mtrand.RandomState.uniform
  File "_common.pyx", line 579, in numpy.random._common.cont
  File "_common.pyx", line 496, in numpy.random._common.cont_broadcast_2
  File "__init__.pxd", line 742, in numpy.PyArray_MultiIterNew3
ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (10, 2) and arg 1 with shape (10, 6).
2022-04-11 11:13:09,784 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (2,)
Traceback (most recent call last):
  File "C:\Users\igorp\OneDrive\Pulpit\Studia\Inteligencja Obliczeniowa\venv\lib\site-packages\pyswarms\backend\generators.py", line 81, in generate_swarm
    pos = center * np.random.uniform(
  File "mtrand.pyx", line 1134, in numpy.random.mtrand.RandomState.uniform
  File "_common.pyx", line 579, in numpy.random._common.cont
  File "_common.pyx", line 496, in numpy.random._common.cont_broadcast_2
  File "__init__.pxd", line 742, in numpy.PyArray_MultiIterNew3
ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (10, 2) and arg 1 with shape (10, 6).
2022-04-11 11:15:49,799 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (2,)
Traceback (most recent call last):
  File "C:\Users\igorp\OneDrive\Pulpit\Studia\Inteligencja Obliczeniowa\venv\lib\site-packages\pyswarms\backend\generators.py", line 81, in generate_swarm
    pos = center * np.random.uniform(
  File "mtrand.pyx", line 1134, in numpy.random.mtrand.RandomState.uniform
  File "_common.pyx", line 579, in numpy.random._common.cont
  File "_common.pyx", line 496, in numpy.random._common.cont_broadcast_2
  File "__init__.pxd", line 742, in numpy.PyArray_MultiIterNew3
ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (10, 2) and arg 1 with shape (10, 6).
2022-04-11 11:16:43,922 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (2,)
Traceback (most recent call last):
  File "C:\Users\igorp\OneDrive\Pulpit\Studia\Inteligencja Obliczeniowa\venv\lib\site-packages\pyswarms\backend\generators.py", line 81, in generate_swarm
    pos = center * np.random.uniform(
  File "mtrand.pyx", line 1134, in numpy.random.mtrand.RandomState.uniform
  File "_common.pyx", line 579, in numpy.random._common.cont
  File "_common.pyx", line 496, in numpy.random._common.cont_broadcast_2
  File "__init__.pxd", line 742, in numpy.PyArray_MultiIterNew3
ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (10, 2) and arg 1 with shape (10, 6).
2022-04-11 11:17:24,598 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (2,)
Traceback (most recent call last):
  File "C:\Users\igorp\OneDrive\Pulpit\Studia\Inteligencja Obliczeniowa\venv\lib\site-packages\pyswarms\backend\generators.py", line 81, in generate_swarm
    pos = center * np.random.uniform(
  File "mtrand.pyx", line 1134, in numpy.random.mtrand.RandomState.uniform
  File "_common.pyx", line 579, in numpy.random._common.cont
  File "_common.pyx", line 496, in numpy.random._common.cont_broadcast_2
  File "__init__.pxd", line 742, in numpy.PyArray_MultiIterNew3
ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (10, 2) and arg 1 with shape (10, 6).
2022-04-11 11:21:01,359 - pyswarms.single.global_best - INFO - Optimize for 1000 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-04-11 11:21:01,652 - pyswarms.single.global_best - INFO - Optimization finished | best cost: 0.8603416865717648, best pos: [3.99148935e-04 8.27061125e-01 4.71822018e-01 5.01511461e-02
 9.76788688e-01 9.72497077e-01]
2022-04-11 11:21:31,726 - pyswarms.single.global_best - INFO - Optimize for 1000 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-04-11 11:21:32,019 - pyswarms.single.global_best - INFO - Optimization finished | best cost: 1.0242514142919217, best pos: [0.00811282 0.92578005 0.41286864 0.02857109 0.90148861 0.66254998]
2022-04-11 11:21:44,310 - pyswarms.single.global_best - INFO - Optimize for 1000 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-04-11 11:21:44,600 - pyswarms.single.global_best - INFO - Optimization finished | best cost: 0.9077486201257272, best pos: [0.00509618 0.98998741 0.5110466  0.02183902 0.97323784 0.73811175]
2022-04-11 11:25:47,467 - pyswarms.single.global_best - INFO - Optimize for 1000 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-04-11 11:25:58,903 - pyswarms.single.global_best - INFO - Optimize for 1000 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-04-11 11:25:59,193 - pyswarms.single.global_best - INFO - Optimization finished | best cost: -2.8324243818022437, best pos: [0.44893663 0.44605764 0.99728488 0.99663736 0.57196543 0.182816  ]
2022-04-11 11:27:20,187 - pyswarms.single.global_best - INFO - Optimize for 1000 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-04-11 11:27:20,480 - pyswarms.single.global_best - INFO - Optimization finished | best cost: -2.8273804799825353, best pos: [0.66214424 0.63932704 0.99057227 0.99037055 0.42396615 0.16650711]
2022-04-13 14:49:32,461 - pyswarms.discrete.binary - INFO - Optimize for 30 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9, 'k': 2, 'p': 1}
2022-04-13 14:49:32,509 - pyswarms.discrete.binary - INFO - Optimization finished | best cost: 0.0, best pos: [1 0 1 0 0 0 0 1 0 0 0 1 0 1 1]
2022-04-13 14:50:47,331 - pyswarms.discrete.binary - INFO - Optimize for 30 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9, 'k': 2, 'p': 1}
2022-04-13 14:50:47,371 - pyswarms.discrete.binary - INFO - Optimization finished | best cost: -472.0, best pos: [1 1 1 0 0 1 1 1 1 1 1 1 1 1 1]
2022-04-13 14:51:24,943 - pyswarms.discrete.binary - INFO - Optimize for 30 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9, 'k': 2, 'p': 1}
2022-04-13 14:51:24,983 - pyswarms.discrete.binary - INFO - Optimization finished | best cost: 4.0, best pos: [0 0 0 1 0 1 0 0 1 0 1 0 1 0 1]
2022-04-13 14:51:58,879 - pyswarms.discrete.binary - INFO - Optimize for 30 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9, 'k': 2, 'p': 1}
2022-04-13 14:51:58,915 - pyswarms.discrete.binary - INFO - Optimization finished | best cost: 0.0, best pos: [0 0 1 1 1 1 1 1 0 1 1 0 1 0 0]
2022-04-13 14:54:02,239 - pyswarms.discrete.binary - INFO - Optimize for 30 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9, 'k': 2, 'p': 1}
2022-04-13 14:54:02,269 - pyswarms.discrete.binary - INFO - Optimization finished | best cost: 2.0, best pos: [1 0 0 0 0 1 1 1 0 1 0 1 0 0 1]
2022-04-26 12:22:07,795 - pyswarms.discrete.binary - INFO - Optimize for 30 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9, 'k': 2, 'p': 1}
2022-04-26 12:22:07,827 - pyswarms.discrete.binary - INFO - Optimization finished | best cost: 2.0, best pos: [1 0 0 1 1 0 1 0 0 0 1 0 0 1 1]
2022-04-26 12:22:29,241 - pyswarms.discrete.binary - INFO - Optimize for 30 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9, 'k': 2, 'p': 1}
2022-04-26 12:22:29,282 - pyswarms.discrete.binary - INFO - Optimization finished | best cost: 2.0, best pos: [1 0 1 1 1 0 1 1 1 0 0 0 1 1 0]
2022-04-26 12:22:40,060 - pyswarms.discrete.binary - INFO - Optimize for 30 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9, 'k': 2, 'p': 1}
2022-04-26 12:22:40,092 - pyswarms.discrete.binary - INFO - Optimization finished | best cost: 2.0, best pos: [0 1 0 0 1 0 0 1 0 0 0 1 1 0 1]
2022-04-26 12:22:47,874 - pyswarms.discrete.binary - INFO - Optimize for 30 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9, 'k': 2, 'p': 1}
2022-04-26 12:22:47,906 - pyswarms.discrete.binary - INFO - Optimization finished | best cost: 0.0, best pos: [1 0 0 1 1 0 1 0 0 0 1 0 0 1 1]
2022-04-26 12:22:56,060 - pyswarms.discrete.binary - INFO - Optimize for 30 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9, 'k': 2, 'p': 1}
2022-04-26 12:22:56,100 - pyswarms.discrete.binary - INFO - Optimization finished | best cost: 2.0, best pos: [0 1 0 1 0 0 1 0 1 1 0 0 1 1 0]
2022-04-26 12:23:05,106 - pyswarms.discrete.binary - INFO - Optimize for 30 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9, 'k': 2, 'p': 1}
2022-04-26 12:23:05,138 - pyswarms.discrete.binary - INFO - Optimization finished | best cost: 0.0, best pos: [1 0 1 0 1 1 0 0 1 1 0 0 1 0 1]
